/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PostItem {
  /**
   * Markdown形式の本文
   */
  body: string;
  /**
   * この記事が共同更新状態かどうか (Qiita Teamでのみ有効)
   */
  coediting?: boolean;
  /**
   * この投稿を公開するグループの url_name (null で全体に公開。Qiita Teamでのみ有効)
   */
  group_url_name?: null | string;
  /**
   * 限定共有状態かどうかを表すフラグ (Qiita Teamでは無効)
   */
  private?: boolean;
  /**
   * 記事に付いたタグ一覧
   */
  tags: {
    name: string;
    versions?: string[];
    [k: string]: unknown;
  }[];
  /**
   * 記事のタイトル
   */
  title: string;
  /**
   * Twitterに投稿するかどうか (Twitter連携を有効化している場合のみ有効)
   */
  tweet?: boolean;
  /**
   * 記事のOrganization の url_name を表します。
   */
  organization_url_name?: string | null;
  /**
   * スライドモードが有効を表すフラグ
   */
  slide?: boolean;
  [k: string]: unknown;
}
